# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima

#podcast settings
podcast_url: http://chatterofjudges.cerberos.id.au/
podcast_album_art: /podcast/Whaddya-Know-Joe-Album-Art.png
podcast_title: Chatter of Judges
podcast_owner: Gareth Pye
podcast_email: gareth@cerberos.id.au
podcast_category: Gaming
podcast_subcategory_one: Magic: The Gathering
podcast_subcategory_two: MtG Judging
podcast_explicit: "no"
podcast_author: Gareth Pye
podcast_description: A humble attempt to create some video resources for Judges.
podcast_summary: Discussion of developments in the MtG Judging community, new sets and how all this affects judges and players in Australia and New Zealand.
podcast_subtitle: Live Recorded and minimally edited.
